-- Generated by tools/package_mod.py; regenerate after source edits.
return {
    version = "3.1.0-dev",
    sourceHash = "d681abf36854b613a3673ff34ed4708da492403955263a008ef19456430763be",
    baseCommit = "f91a20e4e36d6d43fddb33e84964c11b77b1bb2e",
    animationHash = "b21539a8e50f075aff862d6b3cbe35c86f8558066ee0292f87400ed93a6746ff",
    workingTree = "development",
    schemaVersion = 2,
}
