-- data/npc_animdb.lua
-- NPC attack animation database
-- Auto-generated by tools/parse_animations.py
-- Do not edit manually; re-run the script to regenerate.
--
-- Usage: local animDB = require("data/npc_animdb")
--        local entry = animDB["213:0"]

return {
  ["100:0"] = {
    {name="Jump", totalFrames=38, windupFrames=19, category="jumping"},
  },
  ["100:1"] = {
    {name="Jump", totalFrames=38, windupFrames=19, category="jumping"},
  },
  ["101:0"] = {
    {name="StompArm", totalFrames=50, windupFrames=10, category="stomping"},
    {name="StompLeg", totalFrames=50, windupFrames=10, category="stomping"},
  },
  ["101:1"] = {
    {name="StompArm", totalFrames=50, windupFrames=10, category="stomping"},
  },
  ["118:0"] = {
    {name="HeadUpShoot", totalFrames=20, windupFrames=8, category="ranged"},
    {name="HeadRightShoot", totalFrames=20, windupFrames=8, category="ranged"},
    {name="HeadDownShoot", totalFrames=20, windupFrames=8, category="ranged"},
    {name="HeadLeftShoot", totalFrames=20, windupFrames=8, category="ranged"},
  },
  ["12:0"] = {
    {name="Attack", totalFrames=20, windupFrames=9, category="ranged"},
  },
  ["15:0"] = {
    {name="Hop", totalFrames=20, windupFrames=9, category="hopping"},
  },
  ["15:1"] = {
    {name="Hop", totalFrames=20, windupFrames=9, category="hopping"},
  },
  ["15:2"] = {
    {name="Hop", totalFrames=20, windupFrames=9, category="hopping"},
  },
  ["15:3"] = {
    {name="Hop", totalFrames=11, windupFrames=4, category="hopping"},
  },
  ["202:0"] = {
    {name="ShootUp", totalFrames=29, windupFrames=11, category="ranged"},
    {name="ShootRight", totalFrames=29, windupFrames=11, category="ranged"},
    {name="ShootDown", totalFrames=29, windupFrames=11, category="ranged"},
    {name="ShootLeft", totalFrames=29, windupFrames=11, category="ranged"},
  },
  ["202:10"] = {
    {name="Shoot1", totalFrames=29, windupFrames=11, category="ranged"},
    {name="Shoot2", totalFrames=29, windupFrames=11, category="ranged"},
    {name="ShootAndRotate1", totalFrames=29, windupFrames=11, category="ranged"},
    {name="ShootAndRotate2", totalFrames=29, windupFrames=11, category="ranged"},
  },
  ["203:0"] = {
    {name="ShootUp", totalFrames=42, windupFrames=16, category="ranged"},
    {name="ShootRight", totalFrames=42, windupFrames=16, category="ranged"},
    {name="ShootDown", totalFrames=42, windupFrames=16, category="ranged"},
    {name="ShootLeft", totalFrames=42, windupFrames=16, category="ranged"},
  },
  ["204:0"] = {
    {name="Shoot", totalFrames=61, windupFrames=24, category="ranged"},
  },
  ["207:2"] = {
    {name="Fire", totalFrames=12, windupFrames=1, category="ranged"},
  },
  ["208:0"] = {
    {name="Jump", totalFrames=31, windupFrames=15, category="jumping"},
  },
  ["20:0"] = {
    {name="JumpDown", totalFrames=64, windupFrames=33, category="slam"},
    {name="JumpUp", totalFrames=15, windupFrames=7, category="jumping"},
  },
  ["212:0"] = {
    {name="JumpDown", totalFrames=18, windupFrames=11, category="slam"},
    {name="JumpUp", totalFrames=22, windupFrames=11, category="jumping"},
  },
  ["213:0"] = {
    {name="JumpDown", totalFrames=18, windupFrames=11, category="jumping"},
  },
  ["214:0"] = {
    {name="Jump", totalFrames=27, windupFrames=13, category="jumping"},
  },
  ["219:0"] = {
    {name="ShootDown", totalFrames=46, windupFrames=18, category="ranged"},
    {name="ShootRight", totalFrames=46, windupFrames=18, category="ranged"},
    {name="ShootUp", totalFrames=46, windupFrames=18, category="ranged"},
    {name="ShootLeft", totalFrames=46, windupFrames=18, category="ranged"},
  },
  ["229:0"] = {
    {name="ShootDown", totalFrames=14, windupFrames=5, category="ranged"},
    {name="ShootUp", totalFrames=14, windupFrames=5, category="ranged"},
    {name="HeadUpShoot", totalFrames=7, windupFrames=2, category="ranged"},
    {name="HeadRightShoot", totalFrames=7, windupFrames=2, category="ranged"},
    {name="HeadDownShoot", totalFrames=7, windupFrames=2, category="ranged"},
    {name="HeadLeftShoot", totalFrames=7, windupFrames=2, category="ranged"},
  },
  ["229:1"] = {
    {name="Shoot", totalFrames=14, windupFrames=5, category="ranged"},
  },
  ["230:0"] = {
    {name="ShootDown", totalFrames=22, windupFrames=8, category="ranged"},
    {name="ShootUp", totalFrames=14, windupFrames=5, category="ranged"},
  },
  ["246:0"] = {
    {name="Hop", totalFrames=26, windupFrames=11, category="hopping"},
    {name="BigJumpUp", totalFrames=12, windupFrames=6, category="jumping"},
    {name="BigJumpDown", totalFrames=38, windupFrames=22, category="slam"},
    {name="Laser", totalFrames=25, windupFrames=22, category="laser"},
  },
  ["246:1"] = {
    {name="Hop", totalFrames=26, windupFrames=11, category="hopping"},
    {name="BigJumpUp", totalFrames=12, windupFrames=6, category="jumping"},
    {name="BigJumpDown", totalFrames=38, windupFrames=22, category="slam"},
  },
  ["247:0"] = {
    {name="Shoot", totalFrames=61, windupFrames=24, category="ranged"},
  },
  ["250:0"] = {
    {name="Jump", totalFrames=27, windupFrames=13, category="jumping"},
  },
  ["253:0"] = {
    {name="ShootDown", totalFrames=14, windupFrames=5, category="ranged"},
    {name="ShootUp", totalFrames=14, windupFrames=5, category="ranged"},
  },
  ["258:0"] = {
    {name="Shooting", totalFrames=21, windupFrames=8, category="ranged"},
  },
  ["260:0"] = {
    {name="SpitNoSkin", totalFrames=21, windupFrames=8, category="ranged"},
    {name="LaserNoSkin", totalFrames=47, windupFrames=14, category="laser"},
  },
  ["260:10"] = {
    {name="Shoot", totalFrames=16, windupFrames=6, category="ranged"},
  },
  ["261:0"] = {
    {name="Spit", totalFrames=16, windupFrames=6, category="ranged"},
  },
  ["261:1"] = {
    {name="Spit", totalFrames=16, windupFrames=6, category="ranged"},
  },
  ["262:0"] = {
    {name="FireRing", totalFrames=45, windupFrames=1, category="ranged"},
    {name="Spit", totalFrames=46, windupFrames=18, category="ranged"},
  },
  ["263:0"] = {
    {name="Shooting", totalFrames=30, windupFrames=12, category="ranged"},
  },
  ["264:0"] = {
    {name="Jumping", totalFrames=22, windupFrames=11, category="jumping"},
    {name="OldJumping", totalFrames=22, windupFrames=11, category="jumping"},
  },
  ["265:0"] = {
    {name="Jumping", totalFrames=16, windupFrames=8, category="jumping"},
    {name="JumpLoop", totalFrames=8, windupFrames=1, category="jumping"},
  },
  ["265:1"] = {
    {name="Jumping", totalFrames=16, windupFrames=8, category="jumping"},
    {name="JumpLoop", totalFrames=8, windupFrames=1, category="jumping"},
    {name="LaserStartDown", totalFrames=34, windupFrames=33, category="laser"},
    {name="LaserLoopDown", totalFrames=7, windupFrames=1, category="laser"},
    {name="LaserEndDown", totalFrames=18, windupFrames=1, category="laser"},
    {name="LaserStartSide", totalFrames=41, windupFrames=40, category="laser"},
    {name="LaserLoopSide", totalFrames=7, windupFrames=1, category="laser"},
    {name="LaserEndSide", totalFrames=18, windupFrames=1, category="laser"},
    {name="LaserStartUp", totalFrames=35, windupFrames=34, category="laser"},
    {name="LaserLoopUp", totalFrames=7, windupFrames=1, category="laser"},
    {name="LaserEndUp", totalFrames=18, windupFrames=1, category="laser"},
  },
  ["266:0"] = {
    {name="Shoot", totalFrames=55, windupFrames=22, category="ranged"},
  },
  ["26:0"] = {
    {name="Shoot", totalFrames=20, windupFrames=8, category="ranged"},
  },
  ["26:1"] = {
    {name="Shoot", totalFrames=20, windupFrames=8, category="ranged"},
  },
  ["26:2"] = {
    {name="Shoot", totalFrames=20, windupFrames=8, category="ranged"},
  },
  ["271:0"] = {
    {name="LaserShot", totalFrames=21, windupFrames=6, category="laser"},
  },
  ["272:0"] = {
    {name="LaserShot", totalFrames=21, windupFrames=6, category="laser"},
  },
  ["273:0"] = {
    {name="HeadShoot", totalFrames=32, windupFrames=12, category="ranged"},
    {name="HeadShoot2Start", totalFrames=24, windupFrames=23, category="ranged"},
    {name="HeadShoot2Loop", totalFrames=24, windupFrames=1, category="ranged"},
    {name="HeadShoot2End", totalFrames=12, windupFrames=1, category="ranged"},
  },
  ["273:1"] = {
    {name="HeadShoot", totalFrames=32, windupFrames=12, category="ranged"},
  },
  ["274:0"] = {
    {name="Shoot1", totalFrames=65, windupFrames=26, category="ranged"},
    {name="Shoot2Start", totalFrames=5, windupFrames=4, category="ranged"},
    {name="Shoot2Loop", totalFrames=9, windupFrames=1, category="ranged"},
    {name="Shoot2End", totalFrames=7, windupFrames=1, category="ranged"},
  },
  ["275:0"] = {
    {name="Shoot1Start", totalFrames=5, windupFrames=4, category="ranged"},
    {name="Shoot1Loop", totalFrames=9, windupFrames=1, category="ranged"},
    {name="Shoot1End", totalFrames=7, windupFrames=1, category="ranged"},
    {name="Shoot2Start", totalFrames=5, windupFrames=4, category="ranged"},
    {name="Shoot2Loop", totalFrames=9, windupFrames=1, category="ranged"},
    {name="Shoot2End", totalFrames=7, windupFrames=1, category="ranged"},
    {name="Shoot3Start", totalFrames=5, windupFrames=4, category="ranged"},
    {name="Shoot3Loop", totalFrames=9, windupFrames=1, category="ranged"},
    {name="Shoot3End", totalFrames=7, windupFrames=1, category="ranged"},
  },
  ["275:1"] = {
    {name="Shoot1Start", totalFrames=5, windupFrames=4, category="ranged"},
    {name="Shoot1Loop", totalFrames=9, windupFrames=1, category="ranged"},
    {name="Shoot1End", totalFrames=7, windupFrames=1, category="ranged"},
    {name="Shoot2Start", totalFrames=5, windupFrames=4, category="ranged"},
    {name="Shoot2Loop", totalFrames=9, windupFrames=1, category="ranged"},
    {name="Shoot2End", totalFrames=7, windupFrames=1, category="ranged"},
    {name="Shoot3Start", totalFrames=5, windupFrames=4, category="ranged"},
    {name="Shoot3Loop", totalFrames=9, windupFrames=1, category="ranged"},
    {name="Shoot3End", totalFrames=7, windupFrames=1, category="ranged"},
  },
  ["27:0"] = {
    {name="Shoot", totalFrames=61, windupFrames=24, category="ranged"},
  },
  ["27:1"] = {
    {name="Shoot", totalFrames=61, windupFrames=24, category="ranged"},
  },
  ["27:3"] = {
    {name="Shoot", totalFrames=71, windupFrames=28, category="ranged"},
    {name="DummyShoot", totalFrames=61, windupFrames=24, category="ranged"},
  },
  ["282:0"] = {
    {name="Hop", totalFrames=30, windupFrames=13, category="hopping"},
  },
  ["285:0"] = {
    {name="ShootDown", totalFrames=46, windupFrames=18, category="ranged"},
    {name="ShootRight", totalFrames=46, windupFrames=18, category="ranged"},
    {name="ShootUp", totalFrames=46, windupFrames=18, category="ranged"},
    {name="ShootLeft", totalFrames=46, windupFrames=18, category="ranged"},
  },
  ["287:0"] = {
    {name="JumpUp", totalFrames=22, windupFrames=11, category="jumping"},
    {name="JumpDown", totalFrames=18, windupFrames=11, category="jumping"},
  },
  ["28:0"] = {
    {name="SpitHori", totalFrames=20, windupFrames=8, category="ranged"},
    {name="SpitDown", totalFrames=20, windupFrames=8, category="ranged"},
    {name="SpitUp", totalFrames=20, windupFrames=8, category="ranged"},
  },
  ["290:0"] = {
    {name="Shoot1", totalFrames=30, windupFrames=12, category="ranged"},
    {name="Shoot2", totalFrames=20, windupFrames=8, category="ranged"},
  },
  ["297:0"] = {
    {name="JumpOut", totalFrames=15, windupFrames=7, category="jumping"},
  },
  ["298:0"] = {
    {name="Shoot", totalFrames=24, windupFrames=9, category="ranged"},
  },
  ["299:0"] = {
    {name="JumpOut", totalFrames=15, windupFrames=7, category="jumping"},
  },
  ["29:0"] = {
    {name="Hop", totalFrames=26, windupFrames=11, category="hopping"},
    {name="BigJumpUp", totalFrames=12, windupFrames=6, category="jumping"},
    {name="BigJumpDown", totalFrames=40, windupFrames=22, category="slam"},
  },
  ["29:1"] = {
    {name="Hop", totalFrames=26, windupFrames=11, category="hopping"},
    {name="BigJumpUp", totalFrames=12, windupFrames=6, category="jumping"},
    {name="BigJumpDown", totalFrames=40, windupFrames=22, category="slam"},
  },
  ["29:2"] = {
    {name="Hop", totalFrames=26, windupFrames=11, category="hopping"},
  },
  ["29:3"] = {
    {name="Hop", totalFrames=23, windupFrames=10, category="hopping"},
    {name="Hop2", totalFrames=23, windupFrames=10, category="hopping"},
  },
  ["302:10"] = {
    {name="ShootAndRotate1", totalFrames=29, windupFrames=11, category="ranged"},
    {name="ShootAndRotate2", totalFrames=29, windupFrames=11, category="ranged"},
  },
  ["303:0"] = {
    {name="Hop", totalFrames=26, windupFrames=11, category="hopping"},
    {name="BigJumpUp", totalFrames=12, windupFrames=6, category="jumping"},
    {name="BigJumpDown", totalFrames=40, windupFrames=22, category="slam"},
  },
  ["305:0"] = {
    {name="Hop", totalFrames=26, windupFrames=11, category="hopping"},
    {name="Hop_old", totalFrames=20, windupFrames=9, category="hopping"},
  },
  ["30:0"] = {
    {name="Shoot", totalFrames=24, windupFrames=9, category="ranged"},
  },
  ["30:1"] = {
    {name="Shoot", totalFrames=24, windupFrames=9, category="ranged"},
  },
  ["30:2"] = {
    {name="Shoot", totalFrames=24, windupFrames=9, category="ranged"},
  },
  ["34:0"] = {
    {name="Hop", totalFrames=26, windupFrames=11, category="hopping"},
    {name="BigJumpUp", totalFrames=12, windupFrames=6, category="jumping"},
    {name="BigJumpDown", totalFrames=40, windupFrames=22, category="slam"},
  },
  ["34:1"] = {
    {name="Hop", totalFrames=26, windupFrames=11, category="hopping"},
    {name="BigJumpUp", totalFrames=12, windupFrames=6, category="jumping"},
    {name="BigJumpDown", totalFrames=40, windupFrames=22, category="slam"},
  },
  ["375:0"] = {
    {name="ShootingDown", totalFrames=13, windupFrames=5, category="ranged"},
    {name="ShootingRight", totalFrames=13, windupFrames=5, category="ranged"},
    {name="ShootingUp", totalFrames=13, windupFrames=5, category="ranged"},
    {name="ShootingLeft", totalFrames=13, windupFrames=5, category="ranged"},
  },
  ["399:0"] = {
    {name="HeadUpShoot", totalFrames=20, windupFrames=8, category="ranged"},
    {name="HeadRightShoot", totalFrames=20, windupFrames=8, category="ranged"},
    {name="HeadDownShoot", totalFrames=20, windupFrames=8, category="ranged"},
    {name="HeadLeftShoot", totalFrames=20, windupFrames=8, category="ranged"},
  },
  ["404:0"] = {
    {name="Shoot", totalFrames=46, windupFrames=18, category="ranged"},
  },
  ["405:0"] = {
    {name="Shooting1", totalFrames=11, windupFrames=4, category="ranged"},
    {name="Shooting3", totalFrames=23, windupFrames=9, category="ranged"},
    {name="Shooting5", totalFrames=35, windupFrames=14, category="ranged"},
    {name="LegacyHeadThrow", totalFrames=29, windupFrames=11, category="ranged"},
    {name="HeadThrowLeft", totalFrames=29, windupFrames=11, category="ranged"},
    {name="HeadThrowRight", totalFrames=29, windupFrames=11, category="ranged"},
  },
  ["406:0"] = {
    {name="JumpUp", totalFrames=17, windupFrames=8, category="jumping"},
    {name="JumpDown", totalFrames=19, windupFrames=5, category="slam"},
    {name="ShootRight", totalFrames=19, windupFrames=7, category="ranged"},
    {name="ShootLeft", totalFrames=19, windupFrames=7, category="ranged"},
    {name="ShootDown", totalFrames=19, windupFrames=7, category="ranged"},
    {name="ShootUp", totalFrames=19, windupFrames=7, category="ranged"},
  },
  ["406:1"] = {
    {name="JumpUp", totalFrames=17, windupFrames=8, category="jumping"},
    {name="JumpDown", totalFrames=19, windupFrames=5, category="slam"},
    {name="ShootRight", totalFrames=19, windupFrames=7, category="ranged"},
    {name="ShootLeft", totalFrames=19, windupFrames=7, category="ranged"},
    {name="ShootDown", totalFrames=19, windupFrames=7, category="ranged"},
    {name="ShootUp", totalFrames=19, windupFrames=7, category="ranged"},
  },
  ["407:0"] = {
    {name="Spit", totalFrames=20, windupFrames=8, category="ranged"},
    {name="LaserStart", totalFrames=15, windupFrames=14, category="laser"},
    {name="LaserLoop", totalFrames=13, windupFrames=1, category="laser"},
    {name="LaserEnd", totalFrames=7, windupFrames=1, category="laser"},
  },
  ["410:0"] = {
    {name="Jumping", totalFrames=16, windupFrames=8, category="jumping"},
    {name="JumpLoop", totalFrames=8, windupFrames=1, category="jumping"},
  },
  ["411:0"] = {
    {name="HandThrow", totalFrames=32, windupFrames=2, category="ranged"},
  },
  ["413:0"] = {
    {name="Jump", totalFrames=26, windupFrames=13, category="jumping"},
    {name="Jump2", totalFrames=26, windupFrames=13, category="jumping"},
  },
  ["42:0"] = {
    {name="Shoot", totalFrames=29, windupFrames=11, category="ranged"},
  },
  ["42:1"] = {
    {name="Shoot", totalFrames=29, windupFrames=11, category="ranged"},
  },
  ["42:2"] = {
    {name="Shoot", totalFrames=29, windupFrames=11, category="ranged"},
  },
  ["43:0"] = {
    {name="JumpDown", totalFrames=64, windupFrames=33, category="slam"},
    {name="JumpUp", totalFrames=15, windupFrames=7, category="jumping"},
  },
  ["43:1"] = {
    {name="JumpDown", totalFrames=64, windupFrames=33, category="slam"},
    {name="JumpUp", totalFrames=15, windupFrames=7, category="jumping"},
  },
  ["45:0"] = {
    {name="EyeLaser", totalFrames=97, windupFrames=2, category="laser"},
  },
  ["45:10"] = {
    {name="Stomp", totalFrames=75, windupFrames=27, category="stomping"},
    {name="QuickStompBegin", totalFrames=44, windupFrames=27, category="stomping"},
    {name="QuickStomp", totalFrames=24, windupFrames=7, category="stomping"},
    {name="QuickStompEnd", totalFrames=55, windupFrames=7, category="stomping"},
  },
  ["54:0"] = {
    {name="Hop", totalFrames=26, windupFrames=11, category="hopping"},
  },
  ["56:0"] = {
    {name="Spit", totalFrames=20, windupFrames=8, category="ranged"},
  },
  ["59:0"] = {
    {name="JumpUpHead", totalFrames=46, windupFrames=23, category="jumping"},
    {name="JumpBody", totalFrames=46, windupFrames=23, category="jumping"},
    {name="JumpDownHead", totalFrames=46, windupFrames=27, category="slam"},
  },
  ["60:0"] = {
    {name="Shoot", totalFrames=20, windupFrames=8, category="ranged"},
  },
  ["60:1"] = {
    {name="ShootOverlay", totalFrames=20, windupFrames=8, category="ranged"},
  },
  ["66:10"] = {
    {name="Throw", totalFrames=20, windupFrames=8, category="ranged"},
  },
  ["678:0"] = {
    {name="SubAnim_Shoot", totalFrames=3, windupFrames=1, category="ranged"},
  },
  ["68:0"] = {
    {name="JumpUp", totalFrames=34, windupFrames=17, category="jumping"},
    {name="JumpDown", totalFrames=67, windupFrames=27, category="slam"},
  },
  ["68:1"] = {
    {name="JumpUp", totalFrames=34, windupFrames=17, category="jumping"},
    {name="JumpDown", totalFrames=67, windupFrames=27, category="slam"},
  },
  ["74:0"] = {
    {name="JumpUp", totalFrames=17, windupFrames=8, category="jumping"},
    {name="JumpDown", totalFrames=62, windupFrames=22, category="slam"},
  },
  ["75:0"] = {
    {name="JumpUp", totalFrames=17, windupFrames=8, category="jumping"},
    {name="JumpDown", totalFrames=62, windupFrames=22, category="slam"},
  },
  ["76:0"] = {
    {name="Hop", totalFrames=38, windupFrames=17, category="hopping"},
    {name="JumpUp", totalFrames=17, windupFrames=8, category="jumping"},
    {name="JumpDown", totalFrames=62, windupFrames=22, category="slam"},
  },
  ["804:0"] = {
    {name="Slam", totalFrames=91, windupFrames=45, category="slam"},
  },
  ["805:0"] = {
    {name="Shoot", totalFrames=17, windupFrames=6, category="ranged"},
  },
  ["809:0"] = {
    {name="Shoot", totalFrames=43, windupFrames=17, category="ranged"},
  },
  ["810:0"] = {
    {name="HopRight", totalFrames=10, windupFrames=4, category="hopping"},
    {name="HopLeft", totalFrames=10, windupFrames=4, category="hopping"},
    {name="HopDown", totalFrames=10, windupFrames=4, category="hopping"},
    {name="HopUp", totalFrames=10, windupFrames=4, category="hopping"},
  },
  ["816:0"] = {
    {name="Throw", totalFrames=32, windupFrames=12, category="ranged"},
  },
  ["816:1"] = {
    {name="Throw", totalFrames=32, windupFrames=12, category="ranged"},
  },
  ["823:0"] = {
    {name="Jump", totalFrames=35, windupFrames=17, category="jumping"},
  },
  ["829:0"] = {
    {name="Shoot", totalFrames=20, windupFrames=8, category="ranged"},
    {name="Jump", totalFrames=28, windupFrames=14, category="jumping"},
    {name="Jump2", totalFrames=28, windupFrames=14, category="jumping"},
    {name="JumpBack", totalFrames=28, windupFrames=27, category="jumping"},
  },
  ["829:1"] = {
    {name="Shoot", totalFrames=20, windupFrames=8, category="ranged"},
    {name="Jump", totalFrames=28, windupFrames=14, category="jumping"},
    {name="JumpBack", totalFrames=28, windupFrames=27, category="jumping"},
  },
  ["830:0"] = {
    {name="Jump", totalFrames=12, windupFrames=6, category="jumping"},
  },
  ["840:0"] = {
    {name="Hop", totalFrames=26, windupFrames=11, category="hopping"},
  },
  ["84:10"] = {
    {name="Stomp", totalFrames=88, windupFrames=26, category="stomping"},
  },
  ["850:1"] = {
    {name="Shoot", totalFrames=22, windupFrames=8, category="ranged"},
  },
  ["851:0"] = {
    {name="Jump", totalFrames=28, windupFrames=14, category="jumping"},
  },
  ["857:0"] = {
    {name="Jump", totalFrames=29, windupFrames=14, category="jumping"},
  },
  ["859:0"] = {
    {name="Shoot", totalFrames=63, windupFrames=25, category="ranged"},
  },
  ["862:0"] = {
    {name="Shoot", totalFrames=10, windupFrames=4, category="ranged"},
  },
  ["869:0"] = {
    {name="Jump", totalFrames=27, windupFrames=13, category="jumping"},
  },
  ["86:0"] = {
    {name="JumpDown", totalFrames=26, windupFrames=15, category="slam"},
    {name="JumpUp", totalFrames=26, windupFrames=13, category="jumping"},
    {name="JumpHori", totalFrames=26, windupFrames=13, category="jumping"},
    {name="ShootDown", totalFrames=20, windupFrames=8, category="ranged"},
    {name="ShootUp", totalFrames=20, windupFrames=8, category="ranged"},
    {name="ShootHori", totalFrames=20, windupFrames=8, category="ranged"},
  },
  ["872:0"] = {
    {name="Hop", totalFrames=20, windupFrames=9, category="hopping"},
  },
  ["884:0"] = {
    {name="HopShort", totalFrames=10, windupFrames=4, category="hopping"},
    {name="Hop", totalFrames=12, windupFrames=5, category="hopping"},
    {name="HopLong", totalFrames=18, windupFrames=8, category="hopping"},
  },
  ["888:0"] = {
    {name="Jump", totalFrames=35, windupFrames=17, category="jumping"},
  },
  ["889:0"] = {
    {name="FlameShoot", totalFrames=12, windupFrames=4, category="ranged"},
  },
  ["88:0"] = {
    {name="Shoot", totalFrames=24, windupFrames=9, category="ranged"},
  },
  ["88:1"] = {
    {name="Shoot", totalFrames=24, windupFrames=9, category="ranged"},
  },
  ["88:2"] = {
    {name="Shoot", totalFrames=24, windupFrames=9, category="ranged"},
  },
  ["900:0"] = {
    {name="Jump", totalFrames=40, windupFrames=20, category="jumping"},
  },
  ["903:0"] = {
    {name="JumpUp", totalFrames=14, windupFrames=7, category="jumping"},
    {name="JumpDown", totalFrames=26, windupFrames=8, category="slam"},
  },
  ["910:0"] = {
    {name="SpitFly", totalFrames=61, windupFrames=24, category="ranged"},
    {name="ThrowHead", totalFrames=44, windupFrames=17, category="ranged"},
    {name="BrimstoneStart", totalFrames=27, windupFrames=26, category="laser"},
    {name="BrimstoneLoop", totalFrames=6, windupFrames=1, category="laser"},
    {name="BrimstoneEnd", totalFrames=26, windupFrames=1, category="laser"},
  },
  ["910:1"] = {
    {name="Jump", totalFrames=40, windupFrames=20, category="jumping"},
    {name="Shoot", totalFrames=49, windupFrames=19, category="ranged"},
  },
  ["911:2"] = {
    {name="SpitDown", totalFrames=35, windupFrames=14, category="ranged"},
  },
  ["912:0"] = {
    {name="LaserAttack", totalFrames=46, windupFrames=13, category="laser"},
    {name="LaserAttackLoop", totalFrames=10, windupFrames=1, category="laser"},
    {name="LaserAttackEnd", totalFrames=14, windupFrames=1, category="laser"},
    {name="ThrowKnife", totalFrames=74, windupFrames=29, category="ranged"},
    {name="ThrowKnife2", totalFrames=74, windupFrames=29, category="ranged"},
    {name="WristAttackRight", totalFrames=66, windupFrames=46, category="slam"},
    {name="WristAttackLeft", totalFrames=66, windupFrames=46, category="slam"},
    {name="WristAttackBoth", totalFrames=66, windupFrames=46, category="slam"},
    {name="ScrapeAttack", totalFrames=26, windupFrames=11, category="slam"},
    {name="ScrapeAttack2", totalFrames=26, windupFrames=11, category="slam"},
    {name="ScrapeAttackDouble", totalFrames=40, windupFrames=18, category="slam"},
    {name="GroundPound", totalFrames=42, windupFrames=21, category="slam"},
    {name="GroundPound2", totalFrames=42, windupFrames=21, category="slam"},
    {name="GroundPound3", totalFrames=42, windupFrames=21, category="slam"},
    {name="GroundPoundDouble", totalFrames=54, windupFrames=27, category="slam"},
    {name="Shoot1", totalFrames=53, windupFrames=21, category="ranged"},
    {name="Shoot2", totalFrames=47, windupFrames=18, category="ranged"},
  },
  ["912:10"] = {
    {name="ShootBegin", totalFrames=24, windupFrames=23, category="ranged"},
    {name="ShootLoop", totalFrames=12, windupFrames=1, category="ranged"},
    {name="ShootEnd", totalFrames=16, windupFrames=1, category="ranged"},
    {name="ShootLeftBegin", totalFrames=24, windupFrames=23, category="ranged"},
    {name="ShootLeftLoop", totalFrames=12, windupFrames=1, category="ranged"},
    {name="ShootLeftEnd", totalFrames=16, windupFrames=1, category="ranged"},
    {name="ShootRightBegin", totalFrames=24, windupFrames=23, category="ranged"},
    {name="ShootRightLoop", totalFrames=12, windupFrames=1, category="ranged"},
    {name="ShootRightEnd", totalFrames=16, windupFrames=1, category="ranged"},
    {name="Chomp", totalFrames=13, windupFrames=5, category="slam"},
    {name="SwipeLeft", totalFrames=37, windupFrames=18, category="slam"},
    {name="SwipeRight", totalFrames=37, windupFrames=18, category="slam"},
    {name="SwipeDown", totalFrames=37, windupFrames=18, category="slam"},
    {name="SwipeUp", totalFrames=37, windupFrames=18, category="slam"},
    {name="JumpUp", totalFrames=27, windupFrames=13, category="jumping"},
    {name="JumpDown", totalFrames=30, windupFrames=5, category="slam"},
  },
  ["913:0"] = {
    {name="Spit", totalFrames=24, windupFrames=9, category="ranged"},
    {name="Spit2", totalFrames=24, windupFrames=9, category="ranged"},
    {name="Throw", totalFrames=28, windupFrames=11, category="ranged"},
  },
  ["914:0"] = {
    {name="Spit", totalFrames=25, windupFrames=10, category="ranged"},
  },
  ["915:0"] = {
    {name="JumpBlast", totalFrames=50, windupFrames=25, category="jumping"},
  },
  ["916:0"] = {
    {name="Swipe", totalFrames=35, windupFrames=15, category="slam"},
    {name="GroundSlam", totalFrames=49, windupFrames=24, category="slam"},
  },
  ["919:0"] = {
    {name="BrimstoneDown", totalFrames=73, windupFrames=25, category="laser"},
    {name="BrimstoneUp", totalFrames=73, windupFrames=25, category="laser"},
    {name="BrimstoneRight", totalFrames=73, windupFrames=25, category="laser"},
    {name="BrimstoneLeft", totalFrames=73, windupFrames=25, category="laser"},
    {name="Fireball", totalFrames=8, windupFrames=1, category="ranged"},
    {name="FireballImpact", totalFrames=17, windupFrames=1, category="ranged"},
    {name="DashAltShoot", totalFrames=39, windupFrames=15, category="ranged"},
  },
  ["920:0"] = {
    {name="JuggleThrow", totalFrames=40, windupFrames=16, category="ranged"},
  },
  ["950:0"] = {
    {name="BrimstoneStartDown", totalFrames=40, windupFrames=39, category="laser"},
    {name="BrimstoneLoopDown", totalFrames=8, windupFrames=1, category="laser"},
    {name="BrimstoneEndDown", totalFrames=12, windupFrames=1, category="laser"},
    {name="BrimstoneStartUp", totalFrames=40, windupFrames=39, category="laser"},
    {name="BrimstoneLoopUp", totalFrames=8, windupFrames=1, category="laser"},
    {name="BrimstoneStartRight", totalFrames=40, windupFrames=39, category="laser"},
    {name="BrimstoneLoopRight", totalFrames=8, windupFrames=1, category="laser"},
    {name="BrimstoneEndRight", totalFrames=12, windupFrames=1, category="laser"},
    {name="GodheadShoot", totalFrames=17, windupFrames=6, category="ranged"},
  },
  ["951:20"] = {
    {name="Spit", totalFrames=53, windupFrames=27, category="ranged"},
    {name="HeadlessSpit", totalFrames=60, windupFrames=24, category="ranged"},
    {name="HorseSpit", totalFrames=25, windupFrames=10, category="ranged"},
  },
  ["951:30"] = {
    {name="ThrowBomb", totalFrames=40, windupFrames=16, category="ranged"},
  },
}
